### ISSUE TITLE
PatternLayout caller level wrong

### ISSUE THREAD

**Issue by nvx** [timbunce/Log-Log4perl-Layout-JSON#2]
When using the PatternLayout placeholders that display information about the caller (%F for example) this module currently shows Logger.pm as being the file where the logging event occurred instead of the correct source file.

I suspect this is due to the caller level not being incremented here: https://github.com/timbunce/Log-Log4perl-Layout-JSON/blob/master/lib/Log/Log4perl/Layout/JSON.pm#L267

**Comment by heikojansen** [comment]
@timbunce : Would be really nice if you could accept pull request #5 (and close #4) and release a new version to CPAN!
Accepting pull req #6 for the new release would be welcome, too, but imho fixing this issue is more important.
Thanks!

**Comment by timbunce** [comment]
Hello @heikojansen and @nvx. I'm sorry for the delay. I'm short on time and am changing jobs. It looks like I won't be using the module. Would either of you like to adopt it, or at least be a co-maintainer?

**Comment by heikojansen** [comment]
I don´t have any grand plans for the module so if anyone has and wants to adopt it, I´ll just step aside (now or in the future).
On the other hand I´d like to see the current pull requests applied and a new version released to CPAN (I´m HJANSEN there). And I´m OK with looking out for the occasional pull request or bug report so being co-maintainer would be OK for me, too.

**Comment by mschout** [comment]
@heikojansen @timbunce I'm willing to take COMAINT on this so we can get these issues fixed and get a new CPAN release done.  I'm MSCHOUT on CPAN.  If @heikojansen wants to do it instead thats ok.  Just trying to pitch in to get the ball rolling as this module is incredibly useful to my employer.

**Comment by mschout** [comment]
Just wanted to ping you again @timbunce about giving me permission to release the fixes to this module.

**Comment by heikojansen** [comment]
I've forked the repo to add another feature which - optionally - allows structured logging by using multiple arguments for the log methods.
Cf. the relevant parts in [https://github.com/timbunce/Log-Log4perl-Layout-JSON/compare/master...heikojansen:develop](https://github.com/timbunce/Log-Log4perl-Layout-JSON/compare/master...heikojansen:develop)
(sorry, no single commit for the feature in that branch)
No matter who ends up as COMAINT I'd be interested in having that added to a future release. What do you think?

**Comment by timbunce** [comment]
For the record, I've passed primary maintainership to @mschout. Thanks Michael!

**Comment by mschout** [comment]
I've just uploaded v0.50, which fixes this issue, as well as adds the utf8 config flag.  @heikojansen I'll look at your additions for a future release.  Feel free to rebase against my fork and submit a PR to me directly https://github.com/mschout/Log-Log4perl-Layout-JSON/commits/master

**Comment by heikojansen** [comment]
Thanks for taking this on (although, personally, I would´ve preferred if you´d kept the existing version numbering scheme).
Will send a PR soon.

**Comment by marcelser** [comment]
Can anyone please update the code on cpan with new version. It doesn't help to only have it here on github

**Comment by marcelser** [comment]
and I have created a new issue because the split function needs the parameter "-1" to be passed to not omit last value it's empty (empty string in this case).

@mschout do you monitor the issues?

**Comment by heikojansen** [comment]
@marcelser cf. the comment by mschout (10. Apr) and have a look at https://metacpan.org/pod/Log::Log4perl::Layout::JSON
Arguably this issue should have already been closed.

**Comment by mschout** [comment]
@marcelser @heikojansen  This repo is no longer the official repo as @timbunce has handed it off to me.  My fork is the official repo of record at this point (and META.json reflects this in current release).  See [https://github.com/mschout/Log-Log4perl-Layout-JSON](https://metacpan.org/release/Log-Log4perl-Layout-JSON) which is the most current release (v0.52).  This issue was fixed in v0.50 on CPAN.

@timbunce can close this issue.

**Comment by timbunce** [comment]
Thanks @mschout!
